"use client";

/**
 * FinancialsTable Component
 * Ledger-style fundamentals view (dense rows, single instrument panel).
 *
 * Requirements: 8.1, 8.2, 8.3, 8.4, 8.5, 8.6
 */

import { DNA_LABEL, DNA_SUBHEADING } from "@/lib/design-dna";
import { FinancialData } from "@/types";
import { useState } from "react";
import { SymbolTabShell, SymbolTabSkeleton } from "@/components/SymbolTabShell";
import {
  MARKET_DOWN_TEXT,
  MARKET_NEUTRAL_TEXT,
  MARKET_UP_TEXT,
} from "@/lib/market-semantics";
import {
  SYMBOL_DIVIDER,
  SYMBOL_HELP_BUTTON,
  SYMBOL_METRIC,
  SYMBOL_METRIC_COMPACT,
  SYMBOL_MUTED_TEXT,
  SYMBOL_SUBTLE_TEXT,
  SYMBOL_TOOLTIP_SURFACE,
} from "@/lib/symbol-ui";

export interface FinancialsTableProps {
  financials: FinancialData | null | undefined;
}

type Favorability = "favorable" | "unfavorable" | "neutral";

interface MetricItem {
  label: string;
  value: string;
  tooltip: string;
  favorability: Favorability;
}

interface MetricSection {
  title: string;
  tooltip: string;
  metrics: MetricItem[];
}

function getFavorabilityColors(favorability: Favorability): string {
  switch (favorability) {
    case "favorable":
      return MARKET_UP_TEXT;
    case "unfavorable":
      return MARKET_DOWN_TEXT;
    default:
      return MARKET_NEUTRAL_TEXT;
  }
}

function formatCurrency(value: number): string {
  if (Math.abs(value) >= 1e12) return `$${(value / 1e12).toFixed(2)}T`;
  if (Math.abs(value) >= 1e9) return `$${(value / 1e9).toFixed(2)}B`;
  if (Math.abs(value) >= 1e6) return `$${(value / 1e6).toFixed(2)}M`;
  return `$${value.toFixed(2)}`;
}

function formatPercent(value: number): string {
  return `${(value * 100).toFixed(2)}%`;
}

function formatRatio(value: number): string {
  return value.toFixed(2);
}

function getMarginFavorability(value: number): Favorability {
  if (value > 0.15) return "favorable";
  if (value < 0.05) return "unfavorable";
  return "neutral";
}

function getPERatioFavorability(value: number): Favorability {
  if (value <= 0) return "unfavorable";
  if (value < 20) return "favorable";
  if (value > 40) return "unfavorable";
  return "neutral";
}

function getPBRatioFavorability(value: number): Favorability {
  if (value <= 0) return "unfavorable";
  if (value < 3) return "favorable";
  if (value > 5) return "unfavorable";
  return "neutral";
}

function getPEGRatioFavorability(value: number): Favorability {
  if (value <= 0) return "unfavorable";
  if (value < 1) return "favorable";
  if (value > 2) return "unfavorable";
  return "neutral";
}

function getGrowthFavorability(value: number): Favorability {
  if (value > 0.1) return "favorable";
  if (value < 0) return "unfavorable";
  return "neutral";
}

function getROEFavorability(value: number): Favorability {
  if (value > 0.15) return "favorable";
  if (value < 0.05) return "unfavorable";
  return "neutral";
}

function getROAFavorability(value: number): Favorability {
  if (value > 0.05) return "favorable";
  if (value < 0.02) return "unfavorable";
  return "neutral";
}

function buildSections(data: FinancialData): MetricSection[] {
  return [
    {
      title: "Key Financial Facts",
      tooltip:
        "Core financial figures that summarize a company's size and profitability. Revenue is total sales, net income is profit after all expenses, and profit margin shows what percentage of revenue becomes profit.",
      metrics: [
        {
          label: "Revenue",
          value: formatCurrency(data.keyFacts.revenue),
          tooltip:
            "Total revenue generated by the company over the most recent reporting period. Higher revenue generally indicates a larger business. Green if positive, red if negative.",
          favorability: data.keyFacts.revenue > 0 ? "favorable" : "unfavorable",
        },
        {
          label: "Net Income",
          value: formatCurrency(data.keyFacts.netIncome),
          tooltip:
            "The company's total profit after subtracting all expenses, taxes, and costs. Green if positive (profitable), red if negative (loss-making).",
          favorability:
            data.keyFacts.netIncome > 0 ? "favorable" : "unfavorable",
        },
        {
          label: "Profit Margin",
          value: formatPercent(data.keyFacts.profitMargin),
          tooltip:
            "The percentage of revenue that becomes profit. Green above 15% (strong), red below 5% (weak), gray in between.",
          favorability: getMarginFavorability(data.keyFacts.profitMargin),
        },
      ],
    },
    {
      title: "Valuation Metrics",
      tooltip:
        "Ratios that help assess whether a stock is priced fairly relative to its earnings, book value, and growth. Lower ratios may suggest better value.",
      metrics: [
        {
          label: "P/E Ratio",
          value: formatRatio(data.valuation.peRatio),
          tooltip:
            "Price-to-Earnings ratio compares the stock price to earnings per share. Green below 20 (potentially undervalued), red above 40 (potentially overvalued) or negative, gray in between.",
          favorability: getPERatioFavorability(data.valuation.peRatio),
        },
        {
          label: "P/B Ratio",
          value: formatRatio(data.valuation.pbRatio),
          tooltip:
            "Price-to-Book ratio compares the stock price to the company's book value per share. Green below 3 (reasonable valuation), red above 5 or negative, gray in between.",
          favorability: getPBRatioFavorability(data.valuation.pbRatio),
        },
        {
          label: "PEG Ratio",
          value: formatRatio(data.valuation.pegRatio),
          tooltip:
            "Price/Earnings-to-Growth ratio factors in expected earnings growth. Green below 1 (undervalued relative to growth), red above 2 or negative, gray in between.",
          favorability: getPEGRatioFavorability(data.valuation.pegRatio),
        },
      ],
    },
    {
      title: "Growth Metrics",
      tooltip:
        "Measures of how quickly the company is expanding its revenue and earnings. Positive growth indicates the business is expanding.",
      metrics: [
        {
          label: "Revenue Growth",
          value: formatPercent(data.growth.revenueGrowth),
          tooltip:
            "Year-over-year percentage change in revenue. Green above 10% (strong growth), red if negative (declining), gray between 0–10%.",
          favorability: getGrowthFavorability(data.growth.revenueGrowth),
        },
        {
          label: "Earnings Growth",
          value: formatPercent(data.growth.earningsGrowth),
          tooltip:
            "Year-over-year percentage change in earnings. Green above 10% (strong growth), red if negative (declining), gray between 0–10%.",
          favorability: getGrowthFavorability(data.growth.earningsGrowth),
        },
      ],
    },
    {
      title: "Profitability Metrics",
      tooltip:
        "Ratios that measure how effectively the company generates profit from its equity, assets, and operations.",
      metrics: [
        {
          label: "ROE",
          value: formatPercent(data.profitability.roe),
          tooltip:
            "Return on Equity measures how effectively the company uses shareholder equity to generate profit. Green above 15% (strong), red below 5% (weak), gray in between.",
          favorability: getROEFavorability(data.profitability.roe),
        },
        {
          label: "ROA",
          value: formatPercent(data.profitability.roa),
          tooltip:
            "Return on Assets measures how efficiently the company uses its total assets to generate profit. Green above 5% (good), red below 2% (weak), gray in between.",
          favorability: getROAFavorability(data.profitability.roa),
        },
        {
          label: "Operating Margin",
          value: formatPercent(data.profitability.operatingMargin),
          tooltip:
            "The percentage of revenue remaining after paying operating expenses. Green above 15% (efficient), red below 5% (thin margins), gray in between.",
          favorability: getMarginFavorability(
            data.profitability.operatingMargin
          ),
        },
      ],
    },
  ];
}

export function FinancialsTable({ financials }: FinancialsTableProps) {
  if (!financials) {
    return (
      <SymbolTabShell
        eyebrow="Fundamentals"
        title="Financials"
        ariaLabel="Financials"
      >
        <SymbolTabSkeleton blocks={4} />
      </SymbolTabShell>
    );
  }

  const sections = buildSections(financials);
  const [keyFacts, ...restSections] = sections;

  return (
    <SymbolTabShell
      eyebrow="Fundamentals"
      title="Financials"
      ariaLabel="Financial data"
    >
      {/* Featured key facts strip */}
      <section
        className={`rounded-lg border p-4 sm:p-5 ${SYMBOL_DIVIDER} bg-stone-100 dark:bg-stone-800`}
        aria-label={keyFacts.title}
      >
        <SectionHeading section={keyFacts} compact />
        <dl className="mt-3 grid grid-cols-1 gap-3 sm:grid-cols-3 sm:gap-4">
          {keyFacts.metrics.map((metric) => (
            <MetricCell key={metric.label} metric={metric} withTooltip />
          ))}
        </dl>
      </section>

      {/* Ledger columns for remaining sections */}
      <div className="mt-6 grid grid-cols-1 gap-6 lg:grid-cols-3 lg:gap-8">
        {restSections.map((section) => (
          <LedgerSection key={section.title} section={section} />
        ))}
      </div>
    </SymbolTabShell>
  );
}

function SectionHeading({
  section,
  compact = false,
}: {
  section: MetricSection;
  compact?: boolean;
}) {
  const [showSectionTooltip, setSectionTooltip] = useState(false);

  return (
    <div
      className="relative flex cursor-help items-center gap-2"
      onMouseEnter={() => setSectionTooltip(true)}
      onMouseLeave={() => setSectionTooltip(false)}
    >
      <h3 className={`font-semibold ${compact ? DNA_LABEL : DNA_SUBHEADING}`}>
        {section.title}
      </h3>
      <span className={SYMBOL_HELP_BUTTON} aria-hidden>
        ?
      </span>
      {showSectionTooltip && (
        <div
          className={SYMBOL_TOOLTIP_SURFACE}
          style={{ top: "calc(100% + 6px)", left: 0 }}
        >
          {section.tooltip}
        </div>
      )}
    </div>
  );
}

function LedgerSection({ section }: { section: MetricSection }) {
  return (
    <section
      className={`border-t pt-5 lg:border-t-0 lg:pt-0 lg:border-l lg:pl-6 first:lg:border-l-0 first:lg:pl-0 ${SYMBOL_DIVIDER}`}
      aria-label={section.title}
    >
      <SectionHeading section={section} />
      <div className="mt-3 space-y-0">
        {section.metrics.map((metric) => (
          <MetricRow key={metric.label} metric={metric} />
        ))}
      </div>
    </section>
  );
}

function MetricCell({
  metric,
  withTooltip = false,
}: {
  metric: MetricItem;
  withTooltip?: boolean;
}) {
  const [showTooltip, setShowTooltip] = useState(false);
  const colors = getFavorabilityColors(metric.favorability);

  return (
    <div>
      <dt
        className={`flex items-center gap-2 text-xs font-medium ${SYMBOL_SUBTLE_TEXT}`}
      >
        {metric.label}
        {withTooltip && (
          <>
            <button
              type="button"
              className={`${SYMBOL_HELP_BUTTON} h-4 w-4 text-[10px]`}
              aria-label={`More info about ${metric.label}`}
              onMouseEnter={() => setShowTooltip(true)}
              onMouseLeave={() => setShowTooltip(false)}
              onFocus={() => setShowTooltip(true)}
              onBlur={() => setShowTooltip(false)}
            >
              ?
            </button>
            {showTooltip && (
              <div
                role="tooltip"
                className={SYMBOL_TOOLTIP_SURFACE}
                style={{ top: "calc(100% + 6px)", left: 0 }}
              >
                {metric.tooltip}
              </div>
            )}
          </>
        )}
      </dt>
      <dd className={`relative mt-1 ${SYMBOL_METRIC} ${colors}`}>
        {metric.value}
      </dd>
    </div>
  );
}

function MetricRow({ metric }: { metric: MetricItem }) {
  const [showTooltip, setShowTooltip] = useState(false);
  const colors = getFavorabilityColors(metric.favorability);

  return (
    <div
      className={`flex items-center justify-between gap-3 border-b py-2.5 last:border-b-0 ${SYMBOL_DIVIDER}`}
    >
      <div className="relative flex min-w-0 items-center gap-2">
        <span className={SYMBOL_MUTED_TEXT}>{metric.label}</span>
        <button
          type="button"
          className={`${SYMBOL_HELP_BUTTON} h-4 w-4 text-[10px]`}
          aria-label={`More info about ${metric.label}`}
          onMouseEnter={() => setShowTooltip(true)}
          onMouseLeave={() => setShowTooltip(false)}
          onFocus={() => setShowTooltip(true)}
          onBlur={() => setShowTooltip(false)}
        >
          ?
        </button>
        {showTooltip && (
          <div
            role="tooltip"
            className={SYMBOL_TOOLTIP_SURFACE}
            style={{ top: "calc(100% + 6px)", left: 0 }}
          >
            {metric.tooltip}
          </div>
        )}
      </div>
      <span className={`shrink-0 ${SYMBOL_METRIC_COMPACT} ${colors}`}>
        {metric.value}
      </span>
    </div>
  );
}
