import { test, expect } from "./fixtures";

test.describe("Financials Tab", () => {
  /**
   * Helper: search for a symbol and navigate to the Financials tab
   */
  async function goToFinancials(
    page: import("@playwright/test").Page,
    symbol: string
  ) {
    await page.goto("http://localhost:3000");
    const searchInput = page.getByPlaceholder(/search stocks/i);
    await searchInput.fill(symbol);
    await searchInput.press("Enter");
    await expect(
      page.getByRole("heading", { name: new RegExp(symbol, "i") })
    ).toBeVisible();
    await page.getByRole("tab", { name: "Financials" }).click();
  }

  test("should display Financials heading when Financials tab is clicked", async ({
    page,
  }) => {
    await goToFinancials(page, "AAPL");
    await expect(page.getByText("Financials")).toBeVisible();
  });

  // Requirement 8.1: Key financial facts
  test("should display Key Financial Facts section", async ({ page }) => {
    await goToFinancials(page, "AAPL");
    await expect(page.getByText("Key Financial Facts")).toBeVisible();
  });

  // Requirement 8.2: Valuation metrics
  test("should display Valuation Metrics section", async ({ page }) => {
    await goToFinancials(page, "AAPL");
    await expect(page.getByText("Valuation Metrics")).toBeVisible();
  });

  // Requirement 8.3: Growth metrics
  test("should display Growth Metrics section", async ({ page }) => {
    await goToFinancials(page, "AAPL");
    await expect(page.getByText("Growth Metrics")).toBeVisible();
  });

  // Requirement 8.4: Profitability metrics
  test("should display Profitability Metrics section", async ({ page }) => {
    await goToFinancials(page, "AAPL");
    await expect(page.getByText("Profitability Metrics")).toBeVisible();
  });

  // Metric labels
  test("should display key financial fact labels", async ({ page }) => {
    await goToFinancials(page, "MSFT");
    await expect(page.getByText("Revenue")).toBeVisible();
    await expect(page.getByText("Net Income")).toBeVisible();
    await expect(page.getByText("Profit Margin")).toBeVisible();
  });

  test("should display valuation metric labels", async ({ page }) => {
    await goToFinancials(page, "MSFT");
    await expect(page.getByText("P/E Ratio")).toBeVisible();
    await expect(page.getByText("P/B Ratio")).toBeVisible();
    await expect(page.getByText("PEG Ratio")).toBeVisible();
  });

  test("should display growth metric labels", async ({ page }) => {
    await goToFinancials(page, "TSLA");
    await expect(page.getByText("Revenue Growth")).toBeVisible();
    await expect(page.getByText("Earnings Growth")).toBeVisible();
  });

  test("should display profitability metric labels", async ({ page }) => {
    await goToFinancials(page, "TSLA");
    await expect(page.getByText("ROE")).toBeVisible();
    await expect(page.getByText("ROA")).toBeVisible();
    await expect(page.getByText("Operating Margin")).toBeVisible();
  });

  // Requirement 8.5: Tooltips
  test("should show tooltip when hovering over Key Financial Facts heading", async ({
    page,
  }) => {
    await goToFinancials(page, "NVDA");
    const heading = page.getByText("Key Financial Facts");
    await expect(heading).toBeVisible();
    const hoverTarget = heading.locator("..");
    await hoverTarget.hover();
    await expect(
      page.getByText(/Core financial figures that summarize/)
    ).toBeVisible({ timeout: 3000 });
  });

  test("should show tooltip when hovering over Valuation Metrics heading", async ({
    page,
  }) => {
    await goToFinancials(page, "NVDA");
    const heading = page.getByText("Valuation Metrics");
    await expect(heading).toBeVisible();
    const hoverTarget = heading.locator("..");
    await hoverTarget.hover();
    await expect(
      page.getByText(/Ratios that help assess whether a stock/)
    ).toBeVisible({ timeout: 3000 });
  });

  test("should show tooltip when hovering over a metric label", async ({
    page,
  }) => {
    await goToFinancials(page, "GOOGL");
    const hoverTarget = page.getByLabel("More info about Revenue");
    await expect(hoverTarget).toBeVisible();
    await hoverTarget.hover();
    await expect(
      page.getByText(/Total revenue generated by the company/)
    ).toBeVisible({ timeout: 3000 });
  });

  // Help icons
  test("should display help icons for sections and metrics", async ({
    page,
  }) => {
    await goToFinancials(page, "AMZN");
    const helpIcons = page.locator("text=?");
    const count = await helpIcons.count();
    // 4 section icons + 11 metric icons = 15
    expect(count).toBeGreaterThanOrEqual(4);
  });

  // Navigation
  test("should switch back to Overview tab from Financials", async ({
    page,
  }) => {
    await goToFinancials(page, "AAPL");
    await expect(page.getByText("Financials")).toBeVisible();
    await page.getByRole("tab", { name: "Overview" }).click();
    await expect(page.getByText("Key Metrics")).toBeVisible();
  });

  // Responsive
  test("should be responsive on mobile viewport", async ({ page }) => {
    await page.setViewportSize({ width: 375, height: 667 });
    await goToFinancials(page, "NFLX");
    await expect(page.getByText("Financials")).toBeVisible();
    await expect(page.getByText("Key Financial Facts")).toBeVisible();
    await expect(page.getByText("Valuation Metrics")).toBeVisible();
  });
});
